# Enable RGB colour 
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

# statusbar
set -g status-position top

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

# Enable mouse control 
set -g mouse on

# start pane numbering with 1 (better for keyboard)
set -g base-index 1
set -g pane-base-index 1

# renumber windows when they're close
set -g renumber-windows on

# use Vi key bindings in copy mode (Prefix-[)
set-window-option -g mode-keys vi

# remap prefix from 'C-b' to 'C-s'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# use the system clipboard when copy
unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel --clipboard"

# split panes using | and -
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# reload config file
bind r source-file ~/.tmux.conf

# pane resizing
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5

# Move pane to a window
bind j choose-window 'join-pane -h -s "%%"' # horizontally
bind J choose-window 'join-pane -s "%%"' # vertically

# Swap windows with < and >
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Remember path when creating a new window
bind c new-window -c "#{pane_current_path}"

# don't rename windows automatically
set-option -g allow-rename off

# Increase history lines (default 2000)
set-option -g history-limit 10000

# Quick Note
bind-key n split-window -h "nvim ~/Documents/notes/personal/"
bind-key N split-window -h "nvim ~/Documents/notes/work/"

# lazygit
bind-key l display-popup -h 90% -w 85% -d "#{pane_current_path}" -E "lazygit"

# lazydocker
bind-key L display-popup -h 90% -w 85% -E "lazydocker"

## Tmux Plugin Manager
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-open'

# set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin "janoamaral/tokyo-night-tmux"

## janoamaral/tokyo-night-tmux settings  #########
## Battery Widget
set -g @tokyo-night-tmux_show_battery_widget 1 ## 0 disabled - 1 enabled
set -g @tokyo-night-tmux_battery_name "BAT1"  # some linux distro have 'BAT0'
set -g @tokyo-night-tmux_battery_low_threshold 21 # default

set -g @sessionx-bind 'o'
set -g @sessionx-ls-command 'lsd --tree --color=always --icon=always'
set -g @continuum-restore "off" # automatically restore tmux sessions on startup


##################################################

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

