# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
linux_display_server x11

# Fonts
font_family      JetBrainsMono NFM
bold_font        JetBrainsMono NFM Bold
italic_font      JetBrainsMono NFM Italic
bold_italic_font JetBrainsMono NFM Bold Italic
disable_ligatures never
font_size 14

# modify_font underline_position 0

# Window layout 
window_padding_width 5

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #ABB2BF
active_tab_background   #2d313b
active_tab_font_style   bold-italic
inactive_tab_foreground #6D8086
inactive_tab_background #1E2127
inactive_tab_font_style normal
tab_bar_background #22262D


# Color scheme
include ./themes/tokyonight_night.conf

cursor_trail 3

# Window management 
map kitty_mod+l next_window
map kitty_mod+h previous_window

# Tab management
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6


# Layout management 
map kitty_mod+\ next_layout

# Bell
enable_audio_bell no
bell_on_tab "🔔"
visual_bell_color none
visual_bell_duration 0.5
window_alert_on_bell yes

